services:
  - type: web
    name: ai-program-factory
    runtime: node
    plan: starter
    region: oregon
    rootDir: ./server
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL
        value: gpt-4o-mini
    autoDeploy: true
    healthCheckPath: /